name: enreda_app
description: Te ayudamos a construir tu futuro.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  google_sign_in: ^6.1.4
  provider: ^6.0.5
  cloud_firestore: ^4.8.2
  firebase_storage: ^11.2.4
  intl: ^0.18.0
  url_launcher: ^6.2.1
  chips_choice: 3.0.1
  toast: ^0.3.0
  firebase_messaging: ^14.6.4
  badges: ^3.1.2
  google_fonts: ^4.0.4
  percent_indicator: ^4.2.3
  responsive_framework: ^1.1.0
  flutter_pdfview: ^1.3.2
  layout: ^1.0.5
  image_picker: ^1.0.4
  share_plus: ^4.0.4
  universal_html: ^2.2.4
  country_code_picker: ^3.0.0
  email_validator: ^2.1.17
  go_router: ^0.9.3
  font_awesome_flutter: ^10.6.0
  fluttertoast: ^8.2.3
  external_app_launcher: ^3.1.0
  flutter_staggered_grid_view: ^0.7.0
  loading_indicator: ^3.1.1
  flutter_rating_bar: 4.0.1
  path_provider: ^2.1.1
  open_file: ^3.3.2
  http: ^0.13.0
  flutter_slidable: ^3.0.1
  equatable: ^2.0.5
  expandable: ^5.0.1
  country_picker: ^2.0.22
  carousel_slider: ^4.2.1
  dots_indicator: ^3.0.0
  pdf: ^3.10.6
  image: ^4.1.3
  cached_network_image: ^3.3.0
  printing: ^5.11.1
  universal_io: ^2.2.2
  datetime_picker_formfield_new: ^2.1.0
  easy_autocomplete: ^1.6.0
  youtube_player_iframe: ^4.0.4
  smooth_star_rating_null_safety: ^1.0.4+2
  awesome_snackbar_content: ^0.1.3
  shared_preferences: ^2.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/enreda-logo.png
    - images/boy_illustration.png
    - images/researching.png
    - images/ic_enreda_bn.png
    - images/ic_enreda.png
    - images/enreda-mdpi.png
    - images/
    - images/learning-girl.png
    - images/ilustracion-competencias.png
    - images/icon-chat.png
    - images/arrow_down.png
    - images/arrow_up.png
    - images/icon-resources-blue.png
    - images/icon-resources-gray.png
    - images/icon-cv.png
    - images/icon-profile-blue.png
    - images/icon-competencies-blue.png
    - images/icon-fav-blue.png
    - images/favorites-illustration.png
    - images/clip-cv.png
    - images/ilustracion-vista-2.png
    - images/ilustracion-vista-3.png
    - images/ilustracion-vista-4.png
    - images/fondo-verde-vista-1.png
    - images/fondo-verde-vista-2.png
    - images/fondo-verde-vista-3.png
    - images/fondo-verde-vista-4.png
    - images/enreda-logo-alone.png
    - images/enreda-logo-text.png
    - images/flecha.png
    - images/icon-download.png
    - images/icon-logout.png
    - images/logo-enreda-blanco.png
    - images/icon-competencias.png
    - images/chica-lateral.png
    - images/placeholder-image.png
    - images/play_store_900x503.png
    - images/app_store_900x503.png
    - images/empty_900x503.png
    - images/identified_900x503.png
    - images/validated_900x503.png
    - images/certified_900x503.png
    - images/user_default.jpg
    - images/resume.svg
    - images/cv-dots-1.svg
    - images/cv-dots-2.svg
    - images/cv-dots-3.svg
    - images/icon-share.png
    - images/background-otros-2X.png
    - images/background-empleo-2X.png
    - images/background-formacion-2X.png
    - images/background-ocio-2X.png
    - images/background-practicas-2X.png
    - images/background-voluntariado-2X.png
    - images/icon-click-fundaula.png
    - images/person-empleo.png
    - images/person-formacion.png
    - images/person-ocio.png
    - images/person-practicas.png
    - images/person-voluntariado.png
    - images/person-otros.png
    - images/person-pildora1.png
    - images/person-pildora2.png
    - images/person-pildora3.png
    - images/background-pildoras.png
    - images/fundaula-logo.png
    - images/placeholder_video.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
