name: enreda_app
description: Te ayudamos a construir tu futuro.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+7

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.5.0
  firebase_auth: ^4.2.6
  google_sign_in: ^5.4.4
  provider: ^6.0.5
  cloud_firestore: ^4.3.2
  firebase_storage: ^11.0.11
  intl: 0.17.0
  url_launcher: ^6.1.9
  chips_choice: 3.0.0
  toast: ^0.3.0
  firebase_messaging: ^14.2.2
  badges: ^3.0.2
  google_fonts: ^4.0.3
  percent_indicator: ^4.2.2
  responsive_framework: ^0.2.0
  flutter_pdfview: ^1.0.4
  auto_route: any
  auto_route_generator: any
  layout: ^1.0.3
  image_picker: ^0.8.6+1
  date_time_picker: 2.1.0
  share_plus: ^4.5.3
  universal_html: 2.0.8
  country_code_picker: ^2.0.2
  email_validator: ^2.0.1
  go_router: ^0.9.3
  font_awesome_flutter: ^10.3.0
  fluttertoast: ^8.0.9
  external_app_launcher: ^3.0.0
  flutter_staggered_grid_view: ^0.6.2
  loading_indicator: ^3.1.0
  flutter_rating_bar: 4.0.1
  path_provider: ^2.0.1
  open_file: ^3.1.0
  http: ^0.13.4
  flutter_slidable: 2.0.0
  equatable: ^2.0.5
  expandable: 5.0.1
  country_picker: ^2.0.16
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0
  pdf: ^3.9.0
  cached_network_image: ^3.2.3
  printing: ^5.10.1
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - images/enreda-logo.png
    - images/boy_illustration.png
    - images/researching.png
    - images/ic_enreda_bn.png
    - images/ic_enreda.png
    - images/enreda-mdpi.png
    - images/
    - images/learning-girl.png
    - images/ilustracion-competencias.png
    - images/icon-chat.png
    - images/arrow_down.png
    - images/arrow_up.png
    - images/icon-resources-blue.png
    - images/icon-resources-gray.png
    - images/icon-cv.png
    - images/icon-profile-blue.png
    - images/icon-competencies-blue.png
    - images/icon-fav-blue.png
    - images/favorites-illustration.png
    - images/clip-cv.png
    - images/ilustracion-vista-2.png
    - images/ilustracion-vista-3.png
    - images/ilustracion-vista-4.png
    - images/fondo-verde-vista-1.png
    - images/fondo-verde-vista-2.png
    - images/fondo-verde-vista-3.png
    - images/fondo-verde-vista-4.png
    - images/enreda-logo-alone.png
    - images/enreda-logo-text.png
    - images/flecha.png
    - images/icon-download.png
    - images/icon-logout.png
    - images/logo-enreda-blanco.png
    - images/icon-competencias.png
    - images/chica-lateral.png
    - images/placeholder-image.png
    - images/play_store_900x503.png
    - images/app_store_900x503.png
    - images/empty_900x503.png
    - images/identified_900x503.png
    - images/validated_900x503.png
    - images/certified_900x503.png
    - images/user_default.jpg
    - images/resume.svg


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
