pluginManagement {
    repositories {
        google() // 👈 ESENCIAL para 'com.android.application'
        mavenCentral()
        gradlePluginPortal()
        maven { url "https://storage.googleapis.com/download.flutter.io" }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google() // 👈 Requiere estar también aquí
        mavenCentral()
        maven { url "https://storage.googleapis.com/download.flutter.io" }
    }
}

rootProject.name = "enreda"
include(":app")
